name: Project8

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: Install
      run: python -m pip install '.[dev]'
    - name: Lint
      run: flake8
    - name: Mypy
      run: mypy -m project8
    - name: Test
      run: pytest
    - name: Install build
      run: python -m pip install build
    - name: Build wheel
      run: python -m build --wheel
